# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hanna Vasconcelos
email: contato@hannavasconcelos.com.br
description: >- # this means to ignore newlines until "baseurl:"
  Cirurgia geral & videolaparoscopia
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hannavasconcelos.com.br" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title/
sass:
  style: compact

social:
  - name: instagram
    title: "Instagram"
    url: "https://www.instagram.com/dra.hannavasconcelos"
  - name: facebook
    title: "Facebook"
    url: "https://www.facebook.com/dra.hannavasconcelos"
  - name: linkedin
    title: "LinkedIn"
    url: "https://www.linkedin.com/in/hanna-vasconcelos-676404134/?originalSubdomain=br"

collections:
  workplaces:
    output: true
    permalink: /:collection/:name/
  publications:
    output: true
    permalink: /:collection/:name/
  testimonials:
    output: true
    permalink: /:collection/:name/
  specialties:
    output: false
  faqs:
    output: false

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
